CREATE TABLE IF NOT EXISTS bookkeeping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name_payment TEXT NOT NULL,
    cost_payment REAL NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
